# Generated by Django 3.0.5 on 2020-05-24 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_product_productcustomfield_snipcartsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_disc',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=2),
            preserve_default=False,
        ),
    ]
