# Generated by Django 3.0.5 on 2020-05-24 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_product_price_disc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price_disc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
