# Generated by Django 3.0.5 on 2020-08-25 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200524_1024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snipcartsettings',
            name='site',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_disc',
        ),
        migrations.AddField(
            model_name='product',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='ProductCustomField',
        ),
        migrations.DeleteModel(
            name='SnipcartSettings',
        ),
    ]
