# Generated by Django 3.0.5 on 2020-08-26 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20200825_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default='Napoje', max_length=255),
            preserve_default=False,
        ),
    ]
