# Generated by Django 3.1 on 2020-09-08 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailcore', '0052_pagelogentry'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('home', '0010_rateproduct'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RateProduct',
        ),
    ]
